package KAG;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import javax.swing.event.MenuEvent;
import javax.swing.event.MenuListener;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class MenuUtama {
    public JPanel panel1;
    private JMenuBar menubar;
    private JPanel centerPanel;
    private JPanel infoPanel;
    public JLabel welcome;
    private JMenu MenuPdUmum;
    private JMenu MenuPdYouth;
    private JMenu MasterData;
    public JMenu Report;
    private JMenuItem LogOut;
    private JMenuItem RegisUmatUmum;
    private JMenuItem RegisUmatYouth;
    private JMenuItem menuDaftarBaru;
    public JMenuItem menuDaftarEvent;
    public JMenuItem menuReportAbsensi;
    public JMenuItem menuJumlahKehadiran;
    private JFrame menuFrame;

    public MenuUtama() {
        initComponents();
        setFrame();
    }


    private void initComponents() {
        menuFrame = new JFrame();
        menubar = new JMenuBar();
        MenuPdUmum = new JMenu("Register");
        MenuPdYouth = new JMenu("PD Youth");
        MasterData = new JMenu("Data");
        Report = new JMenu("Report");
        LogOut = new JMenuItem("Logout");
        menuDaftarBaru = new JMenuItem("Daftar Baru");
        menuDaftarEvent = new JMenuItem("Daftar Event");
        menuReportAbsensi = new JMenuItem("Absensi");
        menuJumlahKehadiran = new JMenuItem("Jumlah Kehadiran");

        RegisUmatUmum = new JMenuItem("Register PD");
        RegisUmatYouth = new JMenuItem("Register Youth");

    }

    private void setFrame() {
        menuFrame.setTitle("Menu Utama");
        menuFrame.setContentPane(panel1);
        menuFrame.setUndecorated(true);
        menuFrame.setExtendedState(JFrame.MAXIMIZED_BOTH);
        menuFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        menuFrame.setLocationRelativeTo(null);
        menuFrame.setJMenuBar(menubar);
        setMenu();
        menuFrame.pack();
        menuFrame.setVisible(true);
    }


    private void setMenu() {
        menubar.add(MenuPdUmum);
        menubar.add(MasterData);
        menubar.add(Report);
        menubar.add(LogOut);
        menubar.setVisible(true);

        MenuPdUmum.add(RegisUmatUmum);
        MasterData.add(menuDaftarBaru);
        MasterData.add(menuDaftarEvent);

        Report.add(menuReportAbsensi);
        Report.add(menuJumlahKehadiran);

        LogOut.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                int dialogResult = JOptionPane.showConfirmDialog(null, "Logout?");
                if (dialogResult == JOptionPane.YES_OPTION) {
                    Login loginFrame = new Login();
                    menuFrame.setVisible(false);

                }
            }
        });

        menuDaftarBaru.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                DaftarBaru dafbar = new DaftarBaru();
                dafbar.DaftarBaruFrame.setVisible(true);
            }
        });

        RegisUmatUmum.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent actionEvent) {
                ChooseEvent choose = new ChooseEvent();
                choose.jenis = "R";
            }
        });

        menuDaftarEvent.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent actionEvent) {

                DaftarEvent daftar = new DaftarEvent();
            }
        });

        menuReportAbsensi.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent actionEvent) {
                ChooseEvent choose = new ChooseEvent();
                choose.jenis = "A";
            }
        });

        menuJumlahKehadiran.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent actionEvent) {
                ChooseYear chooseYear = new ChooseYear();
            }
        });

    }

    public static void main(String[] args) {
        new MenuUtama();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel1.setPreferredSize(new Dimension(800, 600));
        centerPanel = new JPanel();
        centerPanel.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel1.add(centerPanel, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        infoPanel = new JPanel();
        infoPanel.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel1.add(infoPanel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, new Dimension(20, 20), null, 0, false));
        welcome = new JLabel();
        welcome.setText("Label");
        infoPanel.add(welcome, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_NORTHEAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}
